config/routes.rb
Rails.application.routes.draw do
  resources :subjects

end

app/models/subject.rb
class Subject < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/subjects_controller.rb
class SubjectsController < ApplicationController
  before_action :set_subjects, only: [:index, :new, :create]
  before_action :set_subject, only: [:edit, :destroy]
  
  respond_to :html, :js
  
  def index
  end
  
  def new
    @subject = Subject.new
    respond_to do |format|
      format.html
      format.js
    end
  end
  
  def destroy
    @subject.destroy
    set_subjects
    redirect_to subjects_path
  end
  
  def edit
    @subject.update_attributes(subject_params)
  end
  
  def create
    Subject.new(subject_params).save
    respond_to do |format|
      format.html
      format.js
    end
  end
  
  
  private
  
  def subject_params
    params.require(:subject).permit(:name)
  end
  
  def set_subjects
    @subjects = Subject.all
  end
  
  def set_subject
    @subject = Subject.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/subject_helper.rb
module SubjectHelper
end

app/helpers/subjects_helper.rb
module SubjectsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AjaxTest</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/subjects/_form.html.erb
<%= form_for @subject, remote: true do |f| %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/subjects/_subject.html.erb
<%= subject.name %>
<%= link_to 'Show', subject %>
<%= link_to 'Edit', edit_subject_path(subject) %>
<%= link_to 'Destroy', subject, method: :delete, data: { confirm: 'Are you sure?' } %>
<br/>

app/views/subjects/create.js.erb
$('#render-subjects').html("<%= j(render @subjects) %>")
$('#render-subjects').html("<%= j(render @subjects) %>")
$('#subject-form').slideUp(350);

app/views/subjects/edit.html.erb
<h1>Editing subject</h1>

<%= render 'form' %>

<%= link_to 'Show', @subject %> |
<%= link_to 'Back', subjects_path %>

app/views/subjects/index.html.erb
<h1>Listing subjects</h1>

<div id="render-subjects"
     <%= render @subjects %>
</div>

<br>

<div id="subject-form"> 
  <%= link_to 'New Subject', new_subject_path, remote: true %>
</div>

app/views/subjects/new.js.erb
$('#subject-form').html("<%= j (render 'form') %>");
$('#subject-form').slideDown(350);

app/views/subjects/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @subject.name %>
</p>

<%= link_to 'Edit', edit_subject_path(@subject) %> |
<%= link_to 'Back', subjects_path %>